#!/bin/bash

# update and upgrade
sudo apt update && sudo apt upgrade -y

# install cmd tools
sudo apt install curl neovim ltrace git tmux xclip gcc-multilib nasm htop steghide ruby strace gdb -y

# install tpm for tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# install vundle for vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# install vim-plug plugin manager for NVIM
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# install java and ghidra
sudo apt install openjdk-17-jdk -y
cd ~/Downloads/ && wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.1.2_build/ghidra_11.1.2_PUBLIC_20240709.zip -O ghidra.zip
sudo unzip ghidra.zip -d /opt

# install pwntools
sudo apt install python3-pip -y
python3 -m pip install --upgrade pwntools
# sudo apt install python3-pwntools

# install radare2
cd ~/.local/; git clone https://github.com/radareorg/radare2 && ./radare2/sys/install.sh

# install gdb-gef
bash -c "$(curl -fsSL https://gef.blah.cat/sh)"

# install discord
wget "https://discord.com/api/download?platform=linux&format=deb" -O ~/Downloads/discord.deb
sudo dpkg -i ~/Downloads/discord.deb

# download&install sublime stable
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update && sudo apt install sublime-text

# cleanup
sudo apt autoremove -y
cd ~/Downloads; rm ghidra.zip discord.deb
